language: scala

jdk:
  - oraclejdk8

env:
  global:
    - secure: "ojRvH3tLum3vNktummhRJJ3CPmUi8wYoRc2AU79YJfUBK0JDrjhNu20hVIRbOFmoMXLm5EK9KOuymmRL04pVEcOIgi37D8dM1/8eno1qrA4DJ2Ly91cgRAaIaapLOzkfgOoMoIctCS8tIUIiEPLkpNQSN2OQtlT8c5I2EiKPaceYy7VZcp+o5VHJ/1NQderH1Ugvfyfx7GIP96oVStOVpurx9/CBSlW8pHmXSxg2UpaOVJHf/Nq74m/bUxZhpSBJ/D6XT8sYW3rCChQ0HPLdlwzMZwB5AZK9H+bFAw0z3vJXUE4hmvJH+9qGGvu8xF7TIWKXYMzlycSjVAYHqrqtx7szErkY2H9IuMYXigsIodhB46Q9By0nPhn3s5kVSgVaiMGWYMsPRRAiumcoGt5h7UiP1YZbAuAn758lg2Zwgi9YPh1HPkAH9JNlpCZnQ7q+mJnBnX2LaNDuVfovhf0qqyap/3B++ITt2xTZ7dZZ13TGL7DMFpJGxwm96hrbmdGksEGXCQ6PYa+LSihgvHkh2sFdEFEIGKB+Zwp2MwZCRGipYC7ZeKvZ6Nuswq1zwpVkBaWPVS6yyzN9OZiaZMfb23EWbr4xldrx6sRCZB6IG3I2j/ZlWGhbYvdnSZxE9Pl1YD1DvkdX7H69C+Fcx0jypFYD1GLM127KbMaVJS23AgI="

script: .ci/build

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
before_cache:
  - find $HOME/.ivy2/cache/io.crashbox -depth -name "sbt-gpg*" -exec rm -r {} \;
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
